name: Next.js

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Detect Package Manager
        id: detect-package-manager
        run: |
          if [ -f yarn.lock ]; then
            echo "::set-output name=runner::yarn";
          else
            echo "::set-output name=runner::npm";
          fi
      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.runner }} install
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo 'Deploying...'
